if(XDR_INCLUDE_DIR)
  set(XDR_FIND_QUIETLY TRUE)
endif(XDR_INCLUDE_DIR)

find_path(RPC_INCLUDE_DIR "rpc/rpc.h")

if(RPC_INCLUDE_DIR STREQUAL "RPC_INCLUDE_DIR-NOTFOUND")
  find_path(XDR_INCLUDE_DIR "rpc/xdr.h")
  if(NOT XDR_INCLUDE_DIR STREQUAL "XDR_INCLUDE_DIR-NOTFOUND")
    set(REG_HAS_XDR_H 1)
  endif(NOT XDR_INCLUDE_DIR STREQUAL "XDR_INCLUDE_DIR-NOTFOUND")
else(RPC_INCLUDE_DIR STREQUAL "RPC_INCLUDE_DIR-NOTFOUND")
  set(REG_HAS_RPC_H 1)
  set(XDR_INCLUDE_DIR ${RPC_INCLUDE_DIR})
endif(RPC_INCLUDE_DIR STREQUAL "RPC_INCLUDE_DIR-NOTFOUND")

# find the lib and add it if found
find_library(XDR_LIBRARY NAMES rpc xdr_s xdr openxdr)
if(NOT XDR_LIBRARY STREQUAL "XDR_LIBRARY-NOTFOUND")
  set(REG_EXTERNAL_LIBS ${REG_EXTERNAL_LIBS} ${XDR_LIBRARY})
endif(NOT XDR_LIBRARY STREQUAL "XDR_LIBRARY-NOTFOUND")

mark_as_advanced(RPC_INCLUDE_DIR XDR_INCLUDE_DIR XDR_LIBRARY)

# tend not to need a separate lib on Unix systems
# do need one for Windows and Cygwin
include(FindPackageHandleStandardArgs)
if(UNIX)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(XDR DEFAULT_MSG XDR_INCLUDE_DIR)
else(UNIX)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(XDR DEFAULT_MSG XDR_INCLUDE_DIR XDR_LIBRARY)
endif(UNIX)

